import os
import yt_dlp
import requests
from flask import Flask
from threading import Thread
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

# --- CONFIGURATION ---
TOKEN = "8671935397:AAH1EP3e3rJwgzpGj3D-wUhZ6NVigSalHdQ"
# Tera ShrinkMe API Key
SHRINKME_API = "3a2f8b4ff359f2e648329324ead088c695e981b9" 
DEALS_GROUP = "https://t.me/onlineDeals25" 

# --- WEB SERVER (Keep Alive) ---
app_flask = Flask('')
@app_flask.route('/')
def home(): return "ShrinkMe Bot is Running!"

def run_flask():
    app_flask.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

def keep_alive():
    t = Thread(target=run_flask); t.start()

# --- SHRINKME URL SHORTENER ---
def get_short_link(long_url):
    try:
        # ShrinkMe API endpoint
        api_url = f"https://shrinkme.io/api?api={SHRINKME_API}&url={long_url}"
        result = requests.get(api_url).json()
        if result.get("status") == "success":
            return result["shortened_url"]
        return long_url
    except Exception:
        return long_url

# --- BOT LOGIC ---
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 **Insta-MP3 Bot** ready hai!\n\nBas link bhejo aur audio pao.")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text
    if "instagram.com" not in url:
        await update.message.reply_text("❌ Bhai, sirf Instagram link bhejo.")
        return

    wait_msg = await update.message.reply_text("⏳ Processing audio... Sabar rakho.")

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': f'%(title)s.%(ext)s',
        'cookiefile': 'instagram.com_cookies.txt',
        'postprocessors': [{'key': 'FFmpegExtractAudio','preferredcodec': 'mp3','preferredquality': '192'}],
        'quiet': True,
        'no_warnings': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            temp_name = ydl.prepare_filename(info)
            file_path = os.path.splitext(temp_name)[0] + ".mp3"
        
        # ShrinkMe link generation
        short_loot_link = get_short_link(DEALS_GROUP)
        keyboard = [[InlineKeyboardButton("🔥 BEST LOOT DEALS 🛍️ (Click Here) 🔥", url=short_loot_link)]]
        reply_markup = InlineKeyboardMarkup(keyboard)

        await update.message.reply_audio(
            audio=open(file_path, 'rb'), 
            caption="✅ Audio Generated by @onlineDeals25\n\n👇 Niche wali loot deals miss mat karna!",
            reply_markup=reply_markup
        )
        await wait_msg.delete()
        os.remove(file_path)

    except Exception as e:
        if 'wait_msg' in locals(): await wait_msg.delete()
        await update.message.reply_text(f"❌ Error: {str(e)[:50]}")

if __name__ == '__main__':
    keep_alive()
    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    app.run_polling()
    
