import os
import yt_dlp
import requests
from flask import Flask
from threading import Thread
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

# --- CONFIGURATION ---
TOKEN = "8671935397:AAH1EP3e3rJwgzpGj3D-wUhZ6NVigSalHdQ"
API_KEY = "3a2f8b4ff359f2e648329324ead088c695e981b9" 
DEALS_GROUP = "https://t.me/onlineDeals25" 

# --- WEB SERVER ---
app_flask = Flask('')
@app_flask.route('/')
def home(): return "ShrinkMe Bot is Running!"

def run_flask():
    app_flask.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

def keep_alive():
    t = Thread(target=run_flask); t.start()

# --- FIXED SHORTENER FUNCTION ---
def get_short_link(long_url):
    try:
        # ShrinkMe JSON API Call
        api_url = f"https://shrinkme.io/api?api={API_KEY}&url={long_url}"
        response = requests.get(api_url, timeout=10)
        data = response.json() # Response ko JSON mein convert kiya
        
        if data.get("status") == "success":
            return data.get("shortenedUrl")
        return long_url
    except Exception as e:
        print(f"Shortening Error: {e}")
        return long_url

# --- BOT HANDLERS ---
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 Insta-MP3 Bot 🤖 ready hai!\n\nBas link bhejo aur MP3 pao.")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text
    if "instagram.com" not in url:
        return

    wait_msg = await update.message.reply_text("⏳ Processing audio... Wait karo.")

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': f'%(title)s.%(ext)s',
        'cookiefile': 'instagram.com_cookies.txt',
        'postprocessors': [{'key': 'FFmpegExtractAudio','preferredcodec': 'mp3','preferredquality': '192'}],
        'quiet': True,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            temp_name = ydl.prepare_filename(info)
            file_path = os.path.splitext(temp_name)[0] + ".mp3"
        
        # Link Shortening logic
        short_loot_link = get_short_link(DEALS_GROUP)
        
        # Check karne ke liye ki short link mila ya nahi
        btn_text = "🔥 BEST LOOT DEALS 🛍️ (Click Here) 🔥"
        
        keyboard = [[InlineKeyboardButton(btn_text, url=short_loot_link)]]
        reply_markup = InlineKeyboardMarkup(keyboard)

        await update.message.reply_audio(
            audio=open(file_path, 'rb'), 
            caption=f"✅ Audio Generated by @onlineDeals25\n\n👇 Niche wali loot deals dekho!",
            reply_markup=reply_markup
        )
        await wait_msg.delete()
        os.remove(file_path)

    except Exception as e:
        if 'wait_msg' in locals(): await wait_msg.delete()
        await update.message.reply_text(f"❌ Error: {str(e)[:50]}")

if __name__ == '__main__':
    keep_alive()
    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    app.run_polling()
    
