import os
import yt_dlp
import requests
from flask import Flask
from threading import Thread
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

# --- CONFIGURATION ---
TOKEN = "8671935397:AAH1EP3e3rJwgzpGj3D-wUhZ6NVigSalHdQ"
GPLINKS_API = "3a2f8b4ff359f2e648329324ead088c695e981b9"
# Tumhara Deals Group Link
DEALS_GROUP = "https://t.me/onlineDeals25" 

# --- WEB SERVER (Keep Alive) ---
app_flask = Flask('')
@app_flask.route('/')
def home(): return "Techverse Money Bot is Alive!"

def run_flask():
    app_flask.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

def keep_alive():
    t = Thread(target=run_flask)
    t.start()

# --- URL SHORTENER FUNCTION ---
def get_short_link(long_url):
    try:
        # GPLinks API call
        api_url = f"https://gplinks.in/api?api={GPLINKS_API}&url={long_url}"
        result = requests.get(api_url).json()
        if result.get("status") == "success":
            return result["shortened_url"]
        return long_url # Error pe asli link
    except Exception:
        return long_url

# --- BOT LOGIC ---
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("👋 **Insta-MP3 Bot** ready hai!\n\nBas link bhejo aur high-quality MP3 pao.")

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    url = update.message.text
    
    if "instagram.com" not in url:
        await update.message.reply_text("❌ Bhai, sirf Instagram link bhejo.")
        return

    wait_msg = await update.message.reply_text("⏳ Processing with Cookies... (Wait karo)")

    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': f'%(title)s.%(ext)s',
        'cookiefile': 'instagram.com_cookies.txt',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'add_header': [
            'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
        ],
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            temp_name = ydl.prepare_filename(info)
            file_path = os.path.splitext(temp_name)[0] + ".mp3"
        
        # Link short karke button banana
        short_loot_link = get_short_link(DEALS_GROUP)
        keyboard = [[InlineKeyboardButton("🔥 AAJ KI BEST LOOT DEALS (Click Here) 🔥", url=short_loot_link)]]
        reply_markup = InlineKeyboardMarkup(keyboard)

        await update.message.reply_audio(
            audio=open(file_path, 'rb'), 
            caption="✅ Audio Generated by @onlineDeals25\n\n👇 Niche wali loot deals dekho!",
            reply_markup=reply_markup
        )
        
        await wait_msg.delete()
        os.remove(file_path)

    except Exception as e:
        if 'wait_msg' in locals():
            await wait_msg.delete()
        await update.message.reply_text(f"❌ Error aagaya bhai: {str(e)[:50]}")

if __name__ == '__main__':
    keep_alive()
    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    print("🚀 Bot starting with Earning support...")
    app.run_polling()
    
